input SignupInput {
    username: String!
    email: String!
    password: String!
}

input LoginInput {
    email: String!
    password: String!
}

input UpdateProfileInput {
    username: String
    email: String
    password: String
    role: UserRole
}