type User {
    id: String!
    username: String!
    email: String!
    role: UserRole!
    created_at: DateTime!
    updated_at: DateTime!
    deleted_at: DateTime
}

type OAuthAccount {
    id: String!
    user_id: String!
    provider: String!
    provider_user_id: String!
    created_at: DateTime!
    updated_at: DateTime!
}

type Node {
    id: String!
    parent_id: String!
    owner_id: String
    name: String!
    type:NodeType!
    visibility: NodeVisibility!
    created_at: DateTime!
    updated_at: DateTime!
    hidden_at: DateTime
    trashed_at: DateTime
    deleted_at: DateTime
}

type FileVersions {
    id: String!
    node_id: String!
    version_number: Int!
    storage_path: String!
    size: Int!
    creator_id: String!
    created_at: DateTime!
    deleted_at: DateTime
}

type Group {
    id: String!
    name: String!
    creator_id: String!
    created_at: DateTime!
    updated_at: DateTime!
    deleted_at: DateTime
}

type Permission {
    id: String!
    group_id: String!
    list: Boolean!
    read_metadata: Boolean!
    create_file: Boolean!
    create_directory: Boolean!
    rename: Boolean!
    move: Boolean!
    copy: Boolean!
    delete: Boolean!
    restore: Boolean!
    purge: Boolean!
    download: Boolean!
    zip: Boolean!
    share: Boolean!
    change_visibility: Boolean!
    manage_permissions: Boolean!
    change_owner: Boolean!
    created_at: DateTime!
    updated_at: DateTime!
}

type Share {
    id: String!
    user_id: String!
    node_id: String!
    group_id: String!
    status: InvitationStatus!
    created_at: DateTime!
    updated_at: DateTime!
    expired_at: DateTime!
    accepted_at: DateTime
    deleted_at: DateTime
}

type ActivityLog {
    id: String!
    user_id: String!
    node_id: String!
    action: String!
    metadata: JSON
    created_at: DateTime!
}

type UserStorage {
    id: String!
    user_id: String!
    used_bytes: Int!
    quota_bytes: Int!
    created_at: DateTime!
    updated_at: DateTime!
}

type Payment {
    id: String!
    user_id: String!
    amount: Float!
    currency: String!
    status: PaymentStatus!
    transaction_id: String!
    created_at: DateTime!
    updated_at: DateTime!
    paid_at: DateTime
}

type Setting {
    free_storage_gb: Int!
    price_per_gb: Int!
    trash_retention_days: Int!
    created_at: DateTime!
}

type OAuthResponse {
    user: User!
    access_token: String!
    refresh_token: String!
}